source 'http://rubygems.org'

gem 'rails', '2.3.11'
gem 'rack', '1.1.1'
gem 'mysql'
gem 'rake', '0.8.7'
gem 'capistrano'
gem 'holidays'
gem 'multi_json'
gem 'i18n', '0.4.2'
gem 'mongrel', '~> 1.2.0.pre2'
gem 'arel'
gem 'builder'
gem 'bcrypt-ruby'
gem 'rmagick'
gem 'tzinfo'